<?php
/*
 *
 * @category   Community
 * @package    MagentoCenter_Wm
 * @copyright  http://Magentocenter.org
 * @license    Open Software License (OSL 3.0)
 *
 */

/*
 * Webmoney Transfer payment module
 *
 * @author     Magentocenter.org    -   Magento Store Setup, data migration, upgrades and much more!
 *
 */
    echo $this->__('You will be redirected to Q-Cash Payment Gateway website when you place an order.');
        echo "<br />";	
    echo $this->__('<b>Sonali Bank, Trust Bank , Janata Bank, IFIC Bank and Jamuna Bank Card Accepted.</b>');
?>
